name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Accept licenses
      run: yes | sdkmanager --licenses || true

    - name: Create properties files
      env:
        COINCAP_API_KEY: ${{secrets.COINCAP_API_KEY}}
      shell: bash
      run: |
        touch ./local.properties
        echo COINCAP_API_KEY=$COINCAP_API_KEY >> ./production.properties
      
    - name: Run checks with Gradle
      run: |
        ./gradlew ktlintCheck
        ./gradlew :app:testProductionDebugUnitTest
        ./gradlew :app:validateProductionDebugScreenshotTest

    - name: Safe Artifacts
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: screenshot-test-result
        path: ./app/build/reports/screenshotTest/preview/debug/production/
