name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run Gradle command
      uses: Raul6469/android-gradle-action@2.0.0
      with:
        script: :app:testProductionDebugUnitTest
        android-licence: ${{ secrets.ANDROID_LICENCE }}
