name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Run Gradle command
      uses: Raul6469/android-gradle-action@2.0.0
      with:
        script: :app:testProductionDebugUnitTest
        android-licence: ${{ secrets.ANDROID_LICENCE }}
